services:
  - type: web
    name: estpoker
    env: docker
    plan: free
    region: frankfurt
    buildCommand: ./mvnw clean package -DskipTests
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
