services:
  - type: web
    name: estpoker
    plan: free
    region: frankfurt
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/estpoker-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
