name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

# Least-privilege perms for checkout
permissions:
  contents: read

# Cancel previous runs on the same ref to save minutes
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21 (Temurin) with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      # Fast packaging; unit tests can run in a separate workflow if desired
      - name: Maven package (skip tests)
        run: ./mvnw -B -DskipTests --no-transfer-progress package

      # Optional: publish the built JAR for convenience (ignored if none)
      - name: Upload JAR artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: estpoker-app
          path: target/*.jar
          if-no-files-found: ignore
