name: E2E (Playwright)

on:
  # Manuell: blocking
  workflow_dispatch:
  # Push: optional (keine roten Mails)
  push:
    branches: [ "main" ]

jobs:
  e2e:
    name: Run prod E2E (Prod-only)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Secrets als ENV – Tests lesen EP_* direkt
    env:
      EP_BASE_URL: ${{ secrets.EP_BASE_URL }}
      EP_ROOM_URL: ${{ secrets.EP_ROOM_URL }}

    # Push: tolerant (kein Rotspam), manuell: strict
    continue-on-error: ${{ github.event_name != 'workflow_dispatch' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Install Playwright browsers
        # nur wenn Secrets vorhanden ODER manuell gestartet
        if: ${{ github.event_name == 'workflow_dispatch' || (env.EP_BASE_URL != '' && env.EP_ROOM_URL != '') }}
        run: npx playwright install --with-deps

      - name: Run Playwright (Prod-only)
        if: ${{ github.event_name == 'workflow_dispatch' || (env.EP_BASE_URL != '' && env.EP_ROOM_URL != '') }}
        run: npx playwright test --grep "Prod" --reporter=github

      - name: Upload HTML report
        if: ${{ always() && (github.event_name == 'workflow_dispatch' || (env.EP_BASE_URL != '' && env.EP_ROOM_URL != '')) }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Upload traces on failure
        if: ${{ failure() && (github.event_name == 'workflow_dispatch' || (env.EP_BASE_URL != '' && env.EP_ROOM_URL != '')) }}
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results/**/trace.zip
          if-no-files-found: ignore

      - name: Skip note (no prod secrets on push)
        if: ${{ github.event_name != 'workflow_dispatch' && (env.EP_BASE_URL == '' || env.EP_ROOM_URL == '') }}
        run: |
          echo "Skipping E2E: EP_BASE_URL / EP_ROOM_URL not set."
