# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: E2E (Playwright)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Europe/Vienna
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # 🔧 Secrets/Vars → $GITHUB_ENV (keine Linter-Warnungen)
      - name: Resolve EP_BASE_URL
        shell: bash
        run: |
          EP="${{ secrets.EP_BASE_URL }}"
          [ -z "$EP" ] && EP="${{ secrets.E2E_BASE_URL }}"
          [ -z "$EP" ] && EP="${{ vars.EP_BASE_URL }}"
          [ -z "$EP" ] && EP="${{ vars.E2E_BASE_URL }}"
          [ -z "$EP" ] && EP="http://localhost:8080"
          echo "EP_BASE_URL=$EP" >> "$GITHUB_ENV"
          echo "BASE_URL=$EP" >> "$GITHUB_ENV"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers & system deps
        run: npx playwright install --with-deps

      # Optional – nur wenn gegen laufende URL getestet wird
      # - name: Wait for app
      #   run: npx -y wait-on "$EP_BASE_URL" --http-timeout 60000 --timeout 300000

      - name: Run Playwright tests
        run: npx playwright test --reporter=github --config=playwright.config.ts

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload traces & screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
