name: E2E (Playwright)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Europe/Vienna            # DST-sicher
      BASE_URL: ${{ secrets.E2E_BASE_URL }}  # optional; in tests via process.env.BASE_URL nutzen
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: e2e/package-lock.json  # ← anpassen, falls im Root

      - name: Install dependencies
        run: npm ci
        working-directory: e2e   # ← anpassen

      - name: Install Playwright browsers & system deps
        run: npx playwright install --with-deps
        working-directory: e2e

      # Optional: warten bis Ziel-URL gesund ist (wenn gegen Koyeb/Prod getestet wird)
      # - name: Wait for app
      #   run: |
      #     npx -y wait-on $BASE_URL --http-timeout 60000 --timeout 300000
      #   working-directory: e2e

      - name: Run Playwright tests
        run: npx playwright test --reporter=github
        working-directory: e2e

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/playwright-report
          retention-days: 7

      - name: Upload traces & screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: e2e/test-results
          retention-days: 7
