name: E2E (Playwright)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'Base URL (e.g., https://ep.noxvobiscum.at)'
        required: false
        type: string
      room_url:
        description: 'Full room URL (overrides base_url)'
        required: false
        type: string

jobs:
  guardrails:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node -v && npm -v
      - run: npm i
      - run: npm run check

  e2e:
    needs: guardrails
    runs-on: ubuntu-latest
    env:
      # linter-sicher: nur Secrets hier referenzieren
      EP_BASE_URL: ${{ secrets.EP_BASE_URL || '' }}
      EP_ROOM_URL: ${{ secrets.EP_ROOM_URL || '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: node -v && npm -v

      # Inputs aus workflow_dispatch (falls gesetzt) höher priorisieren als Secrets
      - name: Resolve workflow inputs → env
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ -n "${{ inputs.base_url }}" ]; then echo "EP_BASE_URL=${{ inputs.base_url }}" >> $GITHUB_ENV; fi
          if [ -n "${{ inputs.room_url }}" ]; then echo "EP_ROOM_URL=${{ inputs.room_url }}" >> $GITHUB_ENV; fi

      # Skip, wenn keine Ziel-URL vorhanden
      - name: Skip E2E (no URL provided)
        if: ${{ env.EP_BASE_URL == '' && env.EP_ROOM_URL == '' }}
        run: |
          echo "No EP_BASE_URL / EP_ROOM_URL provided. Skipping E2E."
          echo "→ Set a repo secret EP_BASE_URL or EP_ROOM_URL, or pass inputs via workflow_dispatch."

      # Playwright (Runner + Browser) ohne lokale Abhängigkeiten ausführen
      - name: Install Playwright browsers
        if: ${{ env.EP_BASE_URL != '' || env.EP_ROOM_URL != '' }}
        run: npx -y @playwright/test@latest install --with-deps

      - name: Sanity check (runner available)
        if: ${{ env.EP_BASE_URL != '' || env.EP_ROOM_URL != '' }}
        run: npx -y @playwright/test@latest --version

      - name: Run Playwright E2E
        if: ${{ env.EP_BASE_URL != '' || env.EP_ROOM_URL != '' }}
        env:
          EP_BASE_URL: ${{ env.EP_BASE_URL }}
          EP_ROOM_URL: ${{ env.EP_ROOM_URL }}
        run: npx -y @playwright/test@latest test tests/toggles.spec.js --reporter=line
