name: E2E (Playwright)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TZ: Europe/Vienna
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Resolve EP_BASE_URL from secrets/vars; fallback to localhost
      - name: Resolve EP_BASE_URL (lint-friendly)
        env:
          EP1: ${{ secrets.EP_BASE_URL }}
          EP2: ${{ secrets.E2E_BASE_URL }}
          EP3: ${{ vars.EP_BASE_URL }}
          EP4: ${{ vars.E2E_BASE_URL }}
        shell: bash
        run: |
          EP="${EP1:-${EP2:-${EP3:-${EP4:-http://localhost:8080}}}}"
          echo "EP_BASE_URL=$EP" >> "$GITHUB_ENV"
          echo "BASE_URL=$EP" >> "$GITHUB_ENV"

      - name: Set up Java 21 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      # Start app locally if we are using the localhost fallback
      - name: Start Spring Boot (background)
        if: ${{ endsWith(env.EP_BASE_URL, 'localhost:8080') }}
        run: ./mvnw -DskipTests spring-boot:run &
      
      - name: Wait for app (only when local)
        if: ${{ endsWith(env.EP_BASE_URL, 'localhost:8080') }}
        run: npx -y wait-on "$EP_BASE_URL" --http-timeout 60000 --timeout 300000

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers & system deps
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test -c playwright.config.ts --reporter=github

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7

      - name: Upload traces & screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
          retention-days: 7
